### ISSUE TITLE
Is there a public-facing instance of this server?

### ISSUE THREAD

**Issue by reynoldsnlp** [Harvard-ATG/visualizing_russian_tools#14]
Is there an instance of this server that I can point Russian instructors/learners to, or would I need to spin up my own instance?

**Comment by reynoldsnlp** [comment]
Just saw an email on SEELANGS with the link: http://visualizingrussian.fas.harvard.edu

Would be nice to add this to the README or something like that.

**Comment by arthurian** [comment]
Yes, that's the public version. I just added it to the README. Thanks @reynoldsnlp
